#!/bin/bash

printf "${Bold}\nDeployment values\n${Color_Off}"

printf "\install_trace_enabled: ${install_trace_enabled}"
printf "\n-------------------------------------------------------------------------------------"
printf "\ningress_subdomain_prefix: ${ingress_subdomain_prefix}"
printf "\ningress_secret: ${ingress_secret}"
printf "\ningress_sslPassThrough: ${ingress_sslPassThrough}"
printf "\ningress_https: ${ingress_https}"
printf "\n-------------------------------------------------------------------------------------"
printf "\nimage_pullPolicy: ${image_pullPolicy}"
printf "\nimage_pullSecret: ${image_pullSecret}"
printf "\nimage_tag : ${image_tag}"
printf "\n-------------------------------------------------------------------------------------"
printf "\ndb_type: ${db_type}"
printf "\ndb_host: ${db_host}"
printf "\ndb_port: ${db_port}"
printf "\ndb_name: ${db_name}"
printf "\ndb_userid: ${db_userid}"
printf "\ndb_password: ${db_password}"
printf "\ndb_ssl: ${db_ssl}"
printf "\ndb_adminCredentialsSecret: ${db_adminCredentialsSecret}"
printf "\db_driverPvc_for_oracle_or_mysql: ${db_driverPvc_for_oracle_or_mysql}"
printf "\n-------------------------------------------------------------------------------------"
printf "\ndbinit_enabled: ${dbinit_enabled}"
printf "\ndbinit_resources_requests_cpu: ${dbinit_resources_requests_cpu}"
printf "\ndbinit_resources_requests_memory: ${dbinit_resources_requests_memory}"
printf "\ndbinit_resources_limits_cpu: ${dbinit_resources_limits_cpu}"
printf "\ndbinit_resources_limits_memory: ${dbinit_resources_limits_memory}"
printf "\n-------------------------------------------------------------------------------------"
printf "\nmfpserver_enabled: ${mfpserver_enabled}"
printf "\nmfpserver_consoleUserid: ${mfpserver_consoleUserid}"
printf "\nmfpserver_consolePassword: ${mfpserver_consolePassword}"
printf "\nmfpserver_db_schema: ${mfpserver_db_schema}"
printf "\nmfpserver_internalClientSecretDetails_adminClientSecretId: ${mfpserver_internalClientSecretDetails_adminClientSecretId}"
printf "\nmfpserver_internalClientSecretDetails_adminClientSecretPassword: ${mfpserver_internalClientSecretDetails_adminClientSecretPassword}"
printf "\nmfpserver_internalClientSecretDetails_pushClientSecretId: ${mfpserver_internalClientSecretDetails_pushClientSecretId}"
printf "\nmfpserver_internalClientSecretDetails_pushClientSecretPassword: ${mfpserver_internalClientSecretDetails_pushClientSecretPassword}"
printf "\nmfpserver_adminClientSecret: ${mfpserver_adminClientSecret}"
printf "\nmfpserver_pushClientSecret: ${mfpserver_pushClientSecret}"
printf "\nmfpserver_liveupdateClientSecret: ${mfpserver_liveupdateClientSecret}"
printf "\nmfpserver_replicas: ${mfpserver_replicas}"
printf "\nmfpserver_autoscaling_enabled: ${mfpserver_autoscaling_enabled}"
printf "\nmfpserver_autoscaling_targetcpu: ${mfpserver_autoscaling_targetcpu}"
printf "\nmfpserver_autoscaling_min: ${mfpserver_autoscaling_min}"
printf "\nmfpserver_autoscaling_max: ${mfpserver_autoscaling_max}"
printf "\nmfpserver_pdb_enabled: ${mfpserver_pdb_enabled}"
printf "\nmfpserver_pdb_min: ${mfpserver_pdb_min}"
printf "\nmfpserver_customConfiguration: ${mfpserver_customConfiguration}"
printf "\nmfpserver_keystoreSecret: ${mfpserver_keystoreSecret}"
printf "\nmfpserver_resources_requests_cpu: ${mfpserver_resources_requests_cpu}"
printf "\nmfpserver_resources_requests_memory: ${mfpserver_resources_requests_memory}"
printf "\nmfpserver_resources_limits_cpu: ${mfpserver_resources_limits_cpu}"
printf "\nmfpserver_resources_limits_memory: ${mfpserver_resources_limits_memory}"
printf "\n-------------------------------------------------------------------------------------"
printf "\nmfppush_enabled: ${mfppush_enabled}"
printf "\nmfppush_replicas: ${mfppush_replicas}"
printf "\nmfppush_autoscaling_enabled: ${mfppush_autoscaling_enabled}"
printf "\nmfppush_autoscaling_targetcpu: ${mfppush_autoscaling_targetcpu}"
printf "\nmfppush_autoscaling_min: ${mfppush_autoscaling_min}"
printf "\nmfppush_autoscaling_max: ${mfppush_autoscaling_max}"
printf "\nmfppush_pdb_enabled: ${mfppush_pdb_enabled}"
printf "\nmfppush_pdb_min: ${mfppush_pdb_min}"
printf "\nmfppush_customConfiguration: ${mfppush_customConfiguration}"
printf "\nmfppush_keystoreSecret: ${mfppush_keystoreSecret}"
printf "\nmfppush_resources_requests_cpu: ${mfppush_resources_requests_cpu}"
printf "\nmfppush_resources_requests_memory: ${mfppush_resources_requests_memory}"
printf "\nmfppush_resources_limits_cpu: ${mfppush_resources_limits_cpu}"
printf "\nmfppush_resources_limits_memory: ${mfppush_resources_limits_memory}"
printf "\n-------------------------------------------------------------------------------------"
printf "\nmfpliveupdate_enabled: ${mfpliveupdate_enabled}"
printf "\nmfpliveupdate_replicas: ${mfpliveupdate_replicas}"
printf "\nmfpliveupdate_db_schema: ${mfpliveupdate_db_schema}"
printf "\nmfpliveupdate_autoscaling_enabled: ${mfpliveupdate_autoscaling_enabled}"
printf "\nmfpliveupdate_autoscaling_targetcpu: ${mfpliveupdate_autoscaling_targetcpu}"
printf "\nmfpliveupdate_autoscaling_min: ${mfpliveupdate_autoscaling_min}"
printf "\nmfpliveupdate_autoscaling_max: ${mfpliveupdate_autoscaling_max}"
printf "\nmfpliveupdate_pdb_enabled: ${mfpliveupdate_pdb_enabled}"
printf "\nmfpliveupdate_pdb_min: ${mfpliveupdate_pdb_min}"
printf "\nmfpliveupdate_customConfiguration: ${mfpliveupdate_customConfiguration}"
printf "\nmfpliveupdate_keystoreSecret: ${mfpliveupdate_keystoreSecret}"
printf "\nmfpliveupdate_resources_requests_cpu: ${mfpliveupdate_resources_requests_cpu}"
printf "\nmfpliveupdate_resources_requests_memory: ${mfpliveupdate_resources_requests_memory}"
printf "\nmfpliveupdate_resources_limits_cpu: ${mfpliveupdate_resources_limits_cpu}"
printf "\nmfpliveupdate_resources_limits_memory: ${mfpliveupdate_resources_limits_memory}"
printf "\n-------------------------------------------------------------------------------------"
printf "\nmfpanalytics_enabled: ${mfpanalytics_enabled}"
printf "\nmfpanalytics_consoleUserid: ${mfpanalytics_consoleUserid}"
printf "\nmfpanalytics_consolePassword: ${mfpanalytics_consolePassword}"
printf "\nmfpanalytics_replicas: ${mfpanalytics_replicas}"
printf "\nmfpanalytics_autoscaling_enabled: ${mfpanalytics_autoscaling_enabled}"
printf "\nmfpanalytics_autoscaling_targetcpu: ${mfpanalytics_autoscaling_targetcpu}"
printf "\nmfpanalytics_autoscaling_min: ${mfpanalytics_autoscaling_min}"
printf "\nmfpanalytics_autoscaling_max: ${mfpanalytics_autoscaling_max}"
printf "\nmfpanalytics_pdb_enabled: ${mfpanalytics_pdb_enabled}"
printf "\nmfpanalytics_pdb_min: ${mfpanalytics_pdb_min}"
printf "\nmfpanalytics_customConfiguration: ${mfpanalytics_customConfiguration}"
printf "\nmfpanalytics_keystoreSecret: ${mfpanalytics_keystoreSecret}"
printf "\nmfpanalytics_resources_requests_cpu: ${mfpanalytics_resources_requests_cpu}"
printf "\nmfpanalytics_resources_requests_memory: ${mfpanalytics_resources_requests_memory}"
printf "\nmfpanalytics_resources_requests_limits_cpu: ${mfpanalytics_resources_requests_limits_cpu}"
printf "\nmfpanalytics_resources_requests_limits_memory: ${mfpanalytics_resources_requests_limits_memory}"
printf "\n-------------------------------------------------------------------------------------"
printf "\nmfpanalytics_recvr_enabled: ${mfpanalytics_recvr_enabled}"
printf "\nmfpanalytics_recvr_replicas: ${mfpanalytics_recvr_replicas}"
printf "\nmfpanalytics_recvr_autoscaling_enabled: ${mfpanalytics_recvr_autoscaling_enabled}"
printf "\nmfpanalytics_recvr_autoscaling_targetcpu: ${mfpanalytics_recvr_autoscaling_targetcpu}"
printf "\nmfpanalytics_recvr_autoscaling_min: ${mfpanalytics_recvr_autoscaling_min}"
printf "\nmfpanalytics_recvr_autoscaling_max: ${mfpanalytics_recvr_autoscaling_max}"
printf "\nmfpanalytics_recvr_pdb_enabled: ${mfpanalytics_recvr_pdb_enabled}"
printf "\nmfpanalytics_recvr_pdb_min: ${mfpanalytics_recvr_pdb_min}"
printf "\nmfpanalytics_recvr_analyticsRecvrSecret: ${mfpanalytics_recvr_analyticsRecvrSecret}"
printf "\nmfpanalytics_recvr_customConfiguration: ${mfpanalytics_recvr_customConfiguration}"
printf "\nmfpanalytics_recvr_keystoreSecret: ${mfpanalytics_recvr_keystoreSecret}"
printf "\nmfpanalytics_recvr_resources_requests_cpu: ${mfpanalytics_recvr_resources_requests_cpu}"
printf "\nmfpanalytics_recvr_resources_requests_memory: ${mfpanalytics_recvr_resources_requests_memory}"
printf "\nmfpanalytics_recvr_resources_limits_cpu: ${mfpanalytics_recvr_resources_limits_cpu}"
printf "\nmfpanalytics_recvr_resources_limits_memory: ${mfpanalytics_recvr_resources_limits_memory}"
printf "\n-------------------------------------------------------------------------------------"
printf "\nmfpappcenter_enabled: ${mfpappcenter_enabled}"
printf "\nmfpappcenter_consoleUserid: ${mfpappcenter_consoleUserid}"
printf "\nmfpappcenter_consolePassword: ${mfpappcenter_consolePassword}"
printf "\nmfpappcenter_db_schema: ${mfpappcenter_db_schema}"
printf "\nmfpappcenter_customConfiguration: ${mfpappcenter_customConfiguration}"
printf "\nmfpappcenter_keystoreSecret: ${mfpappcenter_keystoreSecret}"
printf "\nmfpappcenter_replicas: ${mfpappcenter_replicas}"
printf "\nmfpappcenter_autoscaling_enabled: ${mfpappcenter_autoscaling_enabled}"
printf "\nmfpappcenter_autoscaling_targetcpu: ${mfpappcenter_autoscaling_targetcpu}"
printf "\nmfpappcenter_autoscaling_min: ${mfpappcenter_autoscaling_min}"
printf "\nmfpappcenter_autoscaling_max: ${mfpappcenter_autoscaling_max}"
printf "\nmfpappcenter_pdb_enabled: ${mfpappcenter_pdb_enabled}"
printf "\nmfpappcenter_pdb_min: ${mfpappcenter_pdb_min}"
printf "\nmfpappcenter_resources_requests_cpu: ${mfpappcenter_resources_requests_cpu}"
printf "\nmfpappcenter_resources_requests_memory: ${mfpappcenter_resources_requests_memory}"
printf "\nmfpappcenter_resources_limits_cpu: ${mfpappcenter_resources_limits_cpu}"
printf "\nmfpappcenter_resources_limits_memory: ${mfpappcenter_resources_limits_memory}"
printf "\n-------------------------------------------------------------------------------------"
printf "\nelasticsearch_namespace: ${elasticsearch_namespace}"
printf "\nelasticsearch_master_replicas: ${elasticsearch_master_replicas}"
printf "\nelasticsearch_client_replicas: ${elasticsearch_client_replicas}"
printf "\nelasticsearch_data_replicas: ${elasticsearch_data_replicas}"
printf "\nelasticsearch_shards: ${elasticsearch_shards}"
printf "\nelasticsearch_replicasPerShard: ${elasticsearch_replicasPerShard}"
printf "\nelasticsearch_persistence_claimName: ${elasticsearch_persistence_claimName}"
printf "\nelasticsearch_persistence_storageClassName: ${elasticsearch_persistence_storageClassName}"
printf "\nelasticsearch_persistence_size: ${elasticsearch_persistence_size}"
printf "\nelasticsearch_data_resources_requests_cpu: ${elasticsearch_data_resources_requests_cpu}"
printf "\nelasticsearch_data_resources_requests_memory: ${elasticsearch_data_resources_requests_memory}"
printf "\nelasticsearch_data_resources_limits_cpu: ${elasticsearch_data_resources_limits_cpu}"
printf "\nelasticsearch_data_resources_limits_memory: ${elasticsearch_data_resources_limits_memory}"
printf "\nelasticsearch_master_resources_requests_cpu: ${elasticsearch_master_resources_requests_cpu}"
printf "\nelasticsearch_master_resources_requests_memory: ${elasticsearch_master_resources_requests_memory}"
printf "\nelasticsearch_master_resources_limits_cpu: ${elasticsearch_master_resources_limits_cpu}"
printf "\nelasticsearch_master_resources_limits_memory: ${elasticsearch_master_resources_limits_memory}"
printf "\n-------------------------------------------------------------------------------------\n"