apiVersion: es.ibm.com/v1
kind: ESOperator
metadata:
  name: sample-es
  labels:
    app.kubernetes.io/name: es-operator
    app.kubernetes.io/instance: es-instance
    app.kubernetes.io/managed-by: helm
    release: es-operator-_IMG_TAG_
spec:
  ###############################################################################
  # Licensed Materials - Property of IBM.
  # Copyright IBM Corporation 2019. All Rights Reserved.
  # U.S. Government Users Restricted Rights - Use, duplication or disclosure
  # restricted by GSA ADP Schedule Contract with IBM Corp.
  #
  # Contributors:
  # IBM Corporation - initial API and implementation
  ###############################################################################
  
  ###############################################################################
  # Default values for ESOperator
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  ###############################################################################
  arch:
    amd64: "3 - Most preferred"
  image:
    pullPolicy: _IMG_PULLPOLICY_
    pullSecret: _ES_IMG_PULLSECRET_
  ###############################################################################
  ## MF Elasticsearch configuration
  ###############################################################################
  repository: _IMG_REPO_/mfpf-elasticsearch
  tag: _IMG_TAG_
  persistence:
    storageClassName: "_ES_PERSISTENCE_STORAGENAME_"
    claimName: "_ES_PERSISTENCE_CLAIMNAME_"
    size: _ES_PERSISTENCE_DISK_SIZE_
  shards: _ES_SHARDS_
  replicasPerShard: _ES_RPLICAS_PER_SHARD_
  resources:
    requests:
      cpu: _ES_RR_CPU_
      memory: _ES_RR_MEM_
    limits:
      cpu: _ES_RL_CPU_
      memory: _ES_RL_MEM_
  masterReplicas: _ES_MASTER_REPLICAS_
  clientReplicas: _ES_CLIENT_REPLICAS_
  dataReplicas: _ES_DATA_REPLICAS_
  dataResources:
    requests:
      cpu: _ES_DATA_RR_CPU_
      memory: _ES_DATA_RR_MEM_
    limits:
      cpu: _ES_DATA_RL_CPU_
      memory: _ES_DATA_RL_MEM_