###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
# IBM Corporation - initial API and implementation
###############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: es-operator
  labels:
    app.kubernetes.io/name: es-operator
    app.kubernetes.io/instance: mf-instance
    app.kubernetes.io/managed-by: helm
    release: es-operator-_IMG_TAG_
imagePullSecrets:
- name: _IMG_PULLSECRET_